name: shellhacksmobile
description: Mobile Flutter Application for Shellhacks

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_countdown_timer: ^1.0.0
  bubble_tab_indicator: ^0.1.4
  google_fonts:
  url_launcher: ^5.4.10
  intl:
  http:
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_svg:
  gradient_text: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

